### ISSUE TITLE
Dependency version conflict to Google Guice in context with XText 2.26

### ISSUE THREAD

**Issue by muehlbrandt** [eclipse-gef/gef#102]
Hello GEF Team,

in our RCP product we have a problem with the dependencies of GEF and XText 2.26 to Google Guice. GEF requires Google Guice version 1.3 (bundle version 3.0.0) and XText version 5.0.1.

A possible solution is to increase the version upper limit constraints to 5.x.x  in the manifest files for all GEF bundles with dependencies to Guice bundles (if hopefully no further API adjustments are necessary).

I will prepare a contribution for it.

**Comment by miklossy** [comment]
Hello @muehlbrandt !

A Pull Request would be very nice!

Please update the Dependency versions to Xtext 2.26, the GEF version to 5.4.0 and increase the GEF component minor versions by one. Please separate the GEF version changes from the other changes in a separate commit.

Thank you in advance!
Tamás

**Comment by miklossy** [comment]
https://github.com/eclipse/gef/pull/104

**Comment by miklossy** [comment]
Thank you for your contribution @[muehlbrandt](https://github.com/muehlbrandt)!

**Comment by miklossy** [comment]
Solved in GEF 5.4.0.
