### ISSUE TITLE
Update Readme to run the examples with Java 11

### ISSUE THREAD

**Issue by vogella** [eclipse-gef/gef#36]
Run the examples describes that we should use Java 8, now that Java 8 is out of free maintenance from Oracle, please update the description to use Java 11.

**Comment by mwienand** [comment]
We updated the instructions w.r.t. OpenJDK 11 and OpenJFX and tested them with multiple machines. It would be very much appreciated if you could try out the new instructions and leave us a message here if it works for you, too!

I used the new setup for developing an Eclipse View using FXCanvasEx and JavaFX for rendering. Doing that I did not experience any problems, neither developing in the IDE, nor running an Eclipse Application and displaying the View.

Additional notes:
 - IMHO 1.8-EE is not required to make this work, but I will wait for more testing before refining the instructions in this regard.
 - Running Eclipse with OpenJDK-11 and JavaFX requires an additional "-Defxclipse.java-modules.dir=..." argument as explained in the README. This is either needed in an Eclipse.ini or as VM arguments in the Launch Config, depending on where JavaFX is needed to run.
 - The same path that needs to be passed to the "-Defxclipse.java-modules.dir" argument for running, also has to be specified in the Prefences->Java FX->SDK-Path for development, as explained in the README.
 - Do not forget to let "-Defxclipse.java-modules.dir" path (and preference setting, respectively) end with "/lib".
