### ISSUE TITLE
Does the DOT Graph view in Eclipse support Html-like-label display? 

### ISSUE THREAD

**Issue by q4828222** [eclipse-gef/gef#7]
I've tried the following method: The plugin version I used was GEF 5.1.0m2 (2017/09/18), using the Importdot method in the Dotimport class to get Graph objects, create Dotgraphview objects --  the DOT  Graph can be displayed in DOT Graph view, but HTML cannot be displayed correctly in the Dot Graph view. Is there any good solution?

**Comment by nyssen** [comment]
Parsing of HTML elements is already supported, while the DOT Graph view is not yet capable of rendering it properly. Please consider https://bugs.eclipse.org/bugs/show_bug.cgi?id=321775 for details.

PS: GEF uses https://bugs.eclipse.org/bugs for tracking issues. Furthermore, such kind of questions can best be handled in the GEF forum at https://www.eclipse.org/forums/index.php?t=thread&frm_id=81.
