### ISSUE TITLE
Provide Eclipse-Installer Profile

### ISSUE THREAD

**Issue by laeubi** [eclipse-gef/gef#86]
It would be nice to have an Eclipse-Installer profile so it is easy for new users to setup a suitable IDE.

**Comment by merks** [comment]
This exists now.  I will want to move this setup to be hosted in the repository itself, but I don't have so much time at the moment.

Note that the setup works best with a new/updated installer which provides a link in the Variables view that one can use to download the JavaFX SDK.

![image](https://github.com/eclipse/gef/assets/208716/8eedea5d-632f-4984-aaaa-fabbba2b1a13)


##
## Creating an Eclipse Development Environment

You can set up a pre-configured IDE for the development of the GEF FX using the following link:

[![Create Eclipse Development Environment for ECF](https://download.eclipse.org/oomph/www/setups/svg/GEF_FX.svg)](https://www.eclipse.org/setups/installer/?url=https://github.com/eclipse-oomph/oomph/blob/master/setups/interim/GEFConfiguration.setup&show=true "Click to open Eclipse-Installer Auto Launch or drag onto your running installer's title area")
