### ISSUE TITLE
duplicate declaration of version ${javafx.version}

### ISSUE THREAD

**Issue by laeubi** [eclipse-gef/gef#87]
Running a maven build from command line I get the following warning

> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for org.eclipse.gef.plugins:org.eclipse.gef.dot:eclipse-plugin:5.1.0-SNAPSHOT
> [WARNING] 'profiles.profile[javafx.dependencies].dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.openjfx:javafx-controls:jar -> duplicate declaration of version ${javafx.version} @ line 52, column 17
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for org.eclipse.gef.plugins:org.eclipse.gef.dot.ide:eclipse-plugin:5.1.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.eclipse.xtend:xtend-maven-plugin is missing. @ line 24, column 12
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for org.eclipse.gef:org.eclipse.gef.dot.tests:eclipse-test-plugin:5.1.0-SNAPSHOT
> [WARNING] 'profiles.profile[javafx.dependencies].dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.openjfx:javafx-controls:jar -> duplicate declaration of version ${javafx.version} @ line 53, column 17
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]

**Comment by nyssen** [comment]
The javafx.version property is defined only once, inside releng/pom.xml. It is used in a profile (related to Java > 1.8) section with the dot and the dot.tests bundle. I do not think that „threatens the stability of our build“.

Best Regards,
Alexander

**Comment by laeubi** [comment]
@nyssen I think that maven complains because the artifact (!) is declared twice (not the actual property)
ones here:
https://github.com/eclipse/gef/blob/master/org.eclipse.gef.dot/pom.xml#L37
and once here:
https://github.com/eclipse/gef/blob/master/org.eclipse.gef.dot/pom.xml#L54

**Comment by nyssen** [comment]
You are right. I overlooked that.

**Comment by miklossy** [comment]
@laeubi Can this issue be closed as fixed?

**Comment by laeubi** [comment]
I can confirm that current master now builds without warnings.
