### ISSUE TITLE
Cannot reduce the visibility of the overridden method waitForEventProcessing()	in DotHighlightingTest.xtend

### ISSUE THREAD

**Issue by laeubi** [eclipse-gef/gef#88]
I'm trying to setup an IDE and has fixed all problems so far but now the compiler complains in Eclipse

```
Description	Resource	Path	Location	Type
Cannot reduce the visibility of the overridden method waitForEventProcessing()	DotHighlightingTest.xtend	/org.eclipse.gef.dot.tests/src/org/eclipse/gef/dot/tests	line: 199 /org.eclipse.gef.dot.tests/src/org/eclipse/gef/dot/tests/DotHighlightingTest.xtend	Xtend Problem
```

The maven build indeed succeeds without a problem.

**Comment by miklossy** [comment]
Thank you for making us aware of that problem!

The method [waitForEventProcessing](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.xtend#L117-L122) has been added to the AbstractHighlightingTest class in Xtext 2.18.

You are using different Xtext versions in the maven build (Xtext 2.17) and in Eclipse (Xtext >=2.18), right? One possible solution would be to ensure that you are using Xtext 2.17 in Eclipse also. An other option would be to rename the `waitForEventProcessing()` method in the `DotHighlightingTest` class in the GEF DOT code base to something else (e.g. prefix it with `_`) to ensure that implementation is compatible with Xtext >= 2.18.

@laeubi: It would be nice if you could come up with a PR to fix that issue.

**Comment by laeubi** [comment]
I have installed "Xtend IDE 2.21.0.v20200302-1509" as suggested by the contribution guidelines. I'll try to provide a PR as soon as by local build has running successful.

**Comment by miklossy** [comment]
That would be awesome!

**Comment by miklossy** [comment]
Thanks for the fix @laeubi !
